language: python

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.24.1

python:
    - "3.6"

sudo: true

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
    - pip install tox tox-travis

before_script:
    - cd devbox && ./run_devbox.sh
    - echo 'UTC' | sudo tee /etc/timezone

script:
    - tox

after_success:
    - pip install codecov
    - codecov -e TOXENV
    - cd ./devbox && docker-compose -f docker-compose.tests.yaml down

notifications:
    email: false