language: python

python:
    - "3.6"

sudo: false

install:
    - pip install tox tox-travis

script:
    - tox

after_success:
    - pip install codecov
    - codecov -e TOXENV

notifications:
    email: false
