version: '3.1'
services:
  dockerize:
    image: jwilder/dockerize
    command: dockerize -wait http://devbox:8080/ -timeout 300s
    depends_on:
      - devbox
    links:
      - devbox
  devbox:
    image: "healthsamurai/devbox:0.4.7"
    depends_on:
      - devbox-db
    ports:
      - 8080:8080
    links:
      - "devbox-db:database"
    env_file:
      - env_tests
    environment:
      AIDBOX_LICENSE_ID: ${AIDBOX_LICENSE_ID_TESTS}
      AIDBOX_LICENSE_KEY: ${AIDBOX_LICENSE_KEY_TESTS}
  devbox-db:
    image: "aidbox/db:11.4.0.2"
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:       devbox
